[webservers]
serverlab-ec2-01 ansible_host=15.168.175.110 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/aws/serverlab-key.pem
serverlab-ec2-02 ansible_host=15.152.101.204 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/aws/serverlab-key.pem
